Trace the origin of values
saab-simc-admin/palletjack pull request #100
Opened 2016-11-18 09:57 UTC by creideiki

When reading a YAML file into a hash tree, attach metadata to each object saying where in which file it came from.

Closes #36.

2016-11-21 09:09 UTC, notCalle requested changes

2016-11-21 09:09 UTC, notCalle commented on lib/traceable.rb
> +#   $dump_with_position = true
Earlier you said `$traceable_string_output_position`, which also seems to be in line with the actual code.

2016-11-21 09:09 UTC, notCalle commented on lib/palletjack/pallet.rb
> +            merge!(tree[0])
I can only guess that this does something similar to `YAML::load_file`. Should be documented, and probably moved to a helper method somewhere (`YAML::Traceable::load_file`, `TraceableYAML::load_file`?) to lessen the distraction from what `Pallet#load` actually does.

2016-11-21 09:09 UTC, notCalle commented on lib/traceable.rb
> +    record_position(TraceableString.new(String(super)), o)
This makes me uneasy, but since the `KeyTransformer` system already makes the same assumption, I guess it won't make things much worse.

2016-11-21 09:09 UTC, notCalle commented on lib/palletjack/keytransformer.rb
> +                new_value.byte = 0
The transformed value could be identified with the transform rule that created it, which would actually be helpful.

2016-11-21 09:09 UTC, notCalle commented on lib/palletjack/version.rb
> +  VERSION = "0.3.1"
Converting all values loaded from a warehouse to strings is an API breaking change, so bump it all the way to `0.4.0`.

2016-11-21 09:09 UTC, notCalle commented on spec/palletjack-pallet_spec.rb
> +    end
```
Failures:

  1) PalletJack::Pallet a loaded pallet has source information for transformed values
     Failure/Error: expect(@pallet['net.dns.domain'].file).to eq "transformed"
     
     NoMethodError:
       undefined method `file' for nil:NilClass
     # ./spec/palletjack-pallet_spec.rb:65:in `block (3 levels) in <top (required)>'
```

2016-11-21 09:09 UTC, notCalle commented on lib/traceable.rb
> +#   $dump_with_position = true
Actually, I'd prefer it to be a class attribute of TraceableString, not a $global.

2016-11-21 09:09 UTC, notCalle commented on lib/traceable.rb
> +  end
The debug format should off by default, like the debug format of `#to_yaml`.

2016-11-21 09:09 UTC, notCalle commented on spec/palletjack-pallet_spec.rb
> +
Why can't we use the normal `YAML::load` to parse `Pallet#to_yaml` anymore?

2016-11-21 11:10 UTC, creideiki commented on spec/palletjack-pallet_spec.rb
> +
Because `YAML::load` loads integers as integers, while the pallet has them as `TraceableString`:s.

2016-11-21 11:10 UTC, creideiki commented on spec/palletjack-pallet_spec.rb
> +    end
Weird. It succeeds here.

2016-11-21 11:42 UTC, creideiki commented on lib/palletjack/keytransformer.rb
> +                new_value.byte = 0
How do you want to identify the transform? They are currently unnamed, arbitrarily long YAML structures.

2016-11-21 12:05 UTC, creideiki commented on spec/palletjack-pallet_spec.rb
> +    end
... and now it breaks. What the *bleep*?

2016-11-21 13:37 UTC, notCalle commented on lib/palletjack/keytransformer.rb
> +                new_value.byte = 0
`Traceable` position for the transform rule that caused the value, so `transforms.yaml` would need to be loaded as a traceable structure.

2016-11-21 16:06 UTC, notCalle commented on spec/palletjack-pallet_spec.rb
> +      @pallet = @jack.fetch(kind:'domain', name:'example.com')
This no longer explicitly tests `Pallet#load`, which was the intended purpose of the original.

2016-11-21 17:21 UTC, notCalle commented on lib/traceable.rb
> +class PositionVisitor < Psych::Visitors::ToRuby
With Ruby 2.1+, the API for this class seems to have been incompatibly changed.

```
      Failure/Error: visitor = PositionVisitor.new
      
      ArgumentError:
        wrong number of arguments (0 for 2)
      # ./lib/traceable.rb:198:in `new'
      # ./lib/traceable.rb:198:in `parse'
      # ./lib/traceable.rb:208:in `block in load_file'
      # ./lib/traceable.rb:207:in `open'
      # ./lib/traceable.rb:207:in `load_file'
      # ./lib/palletjack.rb:27:in `load'
      # ./lib/palletjack.rb:15:in `load'
      # ./spec/palletjack_spec.rb:20:in `block (3 levels) in <top (required)>'
```

2016-11-23 08:55 UTC, notCalle approved these changes

2016-11-23 08:57 UTC, merged

2017-09-13 08:45 UTC, notCalle commented on lib/traceable.rb
> +    record_position(TraceableString.new(String(super)), o)
I guess #135 shows I guessed wrong.