Fix tool setup error handling
saab-simc-admin/palletjack pull request #118
Opened 2017-04-11 15:27 UTC by notCalle

Current error handling during tool setup is very frustrating when developing a tool, because any error raised gets rescued into `abort(usage)`, not just tool usage errors.

Only rescue `OptionParser` related errors, and raise `OptionParser` related errors for usage errors, instead of raising generic errors. Also, prepend the actual error to the usage when the error contains useful information.

2017-04-11 16:24 UTC, creideiki requested changes

2017-04-11 16:24 UTC, creideiki commented on spec/palletjack-tool_spec.rb
> +  it 'does not mask progamming errors as usage' do
But does it mask spelling errors?

2017-04-11 16:36 UTC, notCalle commented
I see no spelling errors.

2017-04-12 08:21 UTC, creideiki approved these changes

2017-04-12 08:21 UTC, merged