RuboCop updates
saab-simc-admin/palletjack pull request #126
Opened 2017-08-25 22:15 UTC by creideiki

Update RuboCop to 0.49, and configure it to always show cop names when run through Rake.

2017-08-26 15:37 UTC, creideiki commented
See also saab-simc-admin/keyvaluedag#21.

2017-09-08 11:46 UTC, notCalle requested changes
See saab-simc-admin/keyvaluedag#21.

2017-09-08 15:54 UTC, notCalle approved these changes

2017-09-08 16:00 UTC, merged

2017-09-11 12:53 UTC, creideiki commented
Since this is an externally visible change, there should have been a changelog entry. I'll write one when I find a sane development environment.