Import `bundle gem` generated scaffolding
saab-simc-admin/palletjack pull request #82
Opened 2016-10-20 14:09 UTC by notCalle

Import the scaffolding that would have been created if we initialized the project with `bundle gem`, instead of starting from scratch. This adds project support for testing and release management, including publishing to a gem server, with the help of `rake`.

Restructure the palletjack-tools files to match bundler requirements and conventions.

2016-10-24 11:05 UTC, creideiki requested changes

2016-10-24 11:05 UTC, creideiki commented on palletjack.gemspec
> +  spec.add_development_dependency "bundler", "~> 1.13"
Is 1.13 really necessary? CentOS 7 gives us 1.7.8, so it would be advantageous if that worked.

2016-10-24 11:05 UTC, creideiki commented on README.md
> +the `.gem` file to [rubygems.org](https://rubygems.org).
Is there a point to pasting generic release instructions which will not work with our processes into this specific file?

2016-10-24 11:05 UTC, creideiki commented on palletjack.gemspec
> +  spec.add_development_dependency "rake", "~> 10.0"
Same here. CentOS 7 has 0.9.6.

2016-10-24 11:05 UTC, creideiki commented on palletjack.gemspec
> +  spec.add_development_dependency "rspec", "~> 3.0"
Same here. CentOS 7 has 2.14.1.

2016-10-24 14:56 UTC, notCalle commented on palletjack.gemspec
> +  spec.add_development_dependency "bundler", "~> 1.13"
Changed to ~>1.7, and it seems to still work.

2016-10-24 14:57 UTC, notCalle commented on palletjack.gemspec
> +  spec.add_development_dependency "rake", "~> 10.0"
Changed to ~>0.9, and it seems to still work.

2016-10-24 14:57 UTC, notCalle commented on palletjack.gemspec
> +  spec.add_development_dependency "rspec", "~> 3.0"
Changed to ~>2.14, and it seems to still work.

2016-10-24 15:05 UTC, notCalle commented on README.md
> +the `.gem` file to [rubygems.org](https://rubygems.org).
Not really, just chunk merged the boilerplate stuff with what was there.

2016-10-25 06:42 UTC, creideiki commented
Dependency versions should be downgraded in `tools/palletjack-tools.gemspec` as well.

2016-10-25 11:13 UTC, creideiki approved these changes

2016-10-25 11:14 UTC, merged