Improved fetch
saab-simc-admin/palletjack pull request #85
Opened 2016-10-25 15:13 UTC by notCalle

Change pallet fetch APIs to match KVDAG vertex filtering.

Make `PalletJack` a subclass of `KVDAG`, which is what is actually is. Break warehouse loading out into its own method, and add a new class method `::load` that will create a new `PalletJack` and load a warehouse. This breaks everything, and bumps gem minor version.

As an added bonus `jack[...].each` can be replaced by `jack.each(...)`.

Depends on saab-simc-admin/keyvaluedag#13. Closes #80.

2016-10-25 15:44 UTC, creideiki requested changes

2016-10-25 15:44 UTC, creideiki commented on tools/exe/palletjack2unbound
> +    service_config = jack.fetch(kind:'service', name: service_name))
Your parentheses are unbalanced.

2016-10-26 07:14 UTC, notCalle commented on tools/exe/palletjack2unbound
> +    service_config = jack.fetch(kind:'service', name: service_name))
Oops, rebalanced.

2016-10-26 09:12 UTC, creideiki approved these changes

2016-10-26 09:13 UTC, merged